name: cl-distilled
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pandas=1.4.1
  - matplotlib=3.5.1
  - seaborn=0.11.2
  - scikit-learn=1.0.2
  - pytorch=1.11.0
  - cudatoolkit=11.3
  - torchvision=0.12.0
  - torchaudio=0.11.0
